const types = {
    // Navigation actions
    NAVIGATE_LOGGED_IN: 'NAVIGATE_LOGGED_IN',
    NAVIGATE_LOGGED_OUT: 'NAVIGATE_LOGGED_OUT',
    NAVIGATE_LOG_IN: 'NAVIGATE_LOG_IN',
    NAVIGATE_LOG_OUT: 'NAVIGATE_LOG_OUT',
    NAVIGATE_REGISTER: 'NAVIGATE_REGISTER',
    NAVIGATE_BACK: 'NAVIGATE_BACK',
    NAVIGATE_OPEN_DRAWER: 'NAVIGATE_OPEN_DRAWER',
    NAVIGATE_CLOSE_DRAWER: 'NAVIGATE_CLOSE_DRAWER',
    NAVIGATE_TOGGLE_DRAWER: 'NAVIGATE_TOGGLE_DRAWER',
    NAVIGATE_SETTINGS: 'NAVIGATE_SETTINGS',
    NAVIGATE_DRAWER_SETTINGS: 'NAVIGATE_DRAWER_SETTINGS',
    NAVIGATE_DRAWER_HOME: 'NAVIGATE_DRAWER_HOME',
    NAVIGATE_OPEN_MODAL: 'NAVIGATE_OPEN_MODAL',
    NAVIGATE_CLOSE_MODAL: 'NAVIGATE_CLOSE_MODAL',

    // Auth actions
    AUTH_LOGGING_IN: 'AUTH_LOGGING_IN',
    AUTH_LOGIN_ERROR: 'AUTH_LOGIN_ERROR',
    AUTH_FACEBOOK_LOGIN_ERROR: 'AUTH_FACEBOOK_LOGIN_ERROR',
    AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
    AUTH_LOGOUT_SUCCESS: 'AUTH_LOGOUT_SUCCESS'
};

export default types