const types = {
    // Navigation actions
    NAVIGATE_LOGGED_IN: 'NAVIGATE_LOGGED_IN',
    NAVIGATE_LOGGED_OUT: 'NAVIGATE_LOGGED_OUT',
    NAVIGATE_SIGN_UP: 'NAVIGATE_SIGN_UP',
    NAVIGATE_BACK: 'NAVIGATE_BACK',
    NAVIGATE_OPEN_DRAWER: 'NAVIGATE_OPEN_DRAWER',
    NAVIGATE_CLOSE_DRAWER: 'NAVIGATE_CLOSE_DRAWER',
    NAVIGATE_TOGGLE_DRAWER: 'NAVIGATE_TOGGLE_DRAWER',
    NAVIGATE_SETTINGS: 'NAVIGATE_SETTINGS',

    // Auth actions
    AUTH_LOGGING_IN: 'AUTH_LOGGING_IN',
    AUTH_LOGIN_ERROR: 'AUTH_LOGIN_ERROR',
    AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS'
};

export default types