import ThemeManager from 'react-native-color-theme';

export default new ThemeManager({
    refundeoTheme: {
        backgroundColor: '#000125',
        backgroundColorOpaque: 'rgba(0,1,37, 0.7)',
        slightlyDarkerColor: '#f0eded',
        inactiveTabColor: '#b5b5b5',
        activeTabColor: '#1985FB',
        activeTabColorOpaque: 'rgba(48,56,128, 0.6)',
        gradientColor: '#587cd6',
        logoutIconColor: '#dd1d00',
        logoutTextColor: '#dd513d',
        cancelButtonColor: '#ac3429',
        addButtonColor: '#a848d1',
        addButtonInnerColor: '#06105b',
        addButtonOuterColor: '#040a48',
        submitButtonColor: '#303880',
        greenButtonColor: '#3aac66',
        facebookColor: '#3B5998',
        errorColor: 'red',
        whiteColor: '#fffbfd',
        completelyWhite: '#ffffff',
        separatorColor: '#eef2ff',
        blackColor: 'black',
        darkTextColor: '#5a5a5a',
        linkColor: 'blue',
        listBackgroundColor: 'rgba(255,255,255,0.1)',
        transparent: 'rgba(0,0,0,0)'
    },
    oldTheme: {
        backgroundColor: '#faf7f7',
        slightlyDarkerColor: '#f0eded',
        inactiveTabColor: '#b5b5b5',
        activeTabColor: '#303880',
        activeTabColorOpaque: 'rgba(48,56,128, 0.6)',
        gradientColor: '#587cd6',
        logoutIconColor: '#dd1d00',
        logoutTextColor: '#dd513d',
        cancelButtonColor: '#ac3429',
        submitButtonColor: '#303880',
        greenButtonColor: '#3aac66',
        facebookColor: '#3B5998',
        errorColor: 'red',
        whiteColor: 'white',
        separatorColor: '#CED0CE',
        blackColor: 'black',
        darkTextColor: '#5a5a5a',
        linkColor: 'blue'
    },
});