source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'Refundeo' do
  # React Native currently does not support use_frameworks!
  # use_frameworks!

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport', # Enables In-App Devmenu
    'RCTText',
    'RCTImage',
    'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation',
  ]

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  
  # Third party pods
  pod 'react-native-document-picker', :path => '../node_modules/react-native-document-picker'
  pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'
  pod 'RNFS', :path => '../node_modules/react-native-fs'
  pod 'RNI18n', :path => '../node_modules/react-native-i18n'
  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'
  pod 'react-native-camera', :path => '../node_modules/react-native-camera'
  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-google-maps'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
    if target.name == "React"
      target.remove_from_project
    end
  end
end