# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'Refundeo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  pod 'react-native-document-picker', :path => '../node_modules/react-native-document-picker'

  pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'RNI18n', :path => '../node_modules/react-native-i18n'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

end
